// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-plgpC8nR-_wDWFNGU7RtrLvGq7MSk2I',
    appId: '1:233586415711:web:3b1151e28d0a504cfb23ea',
    messagingSenderId: '233586415711',
    projectId: 'vigil-cloud-c9e28',
    authDomain: 'vigil-cloud-c9e28.firebaseapp.com',
    storageBucket: 'vigil-cloud-c9e28.firebasestorage.app',
    measurementId: 'G-QXCRB8J4C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvkjx1D7YB6EL-sEbcWtcOfSpogF08so',
    appId: '1:233586415711:android:633b65664e9617d1fb23ea',
    messagingSenderId: '233586415711',
    projectId: 'vigil-cloud-c9e28',
    storageBucket: 'vigil-cloud-c9e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgAql2NzwXUqRfaHkmUxAdgW3WcklQzfI',
    appId: '1:233586415711:ios:4a28a4bb451ea8fcfb23ea',
    messagingSenderId: '233586415711',
    projectId: 'vigil-cloud-c9e28',
    storageBucket: 'vigil-cloud-c9e28.firebasestorage.app',
    iosBundleId: 'com.example.vigilCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgAql2NzwXUqRfaHkmUxAdgW3WcklQzfI',
    appId: '1:233586415711:ios:4a28a4bb451ea8fcfb23ea',
    messagingSenderId: '233586415711',
    projectId: 'vigil-cloud-c9e28',
    storageBucket: 'vigil-cloud-c9e28.firebasestorage.app',
    iosBundleId: 'com.example.vigilCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-plgpC8nR-_wDWFNGU7RtrLvGq7MSk2I',
    appId: '1:233586415711:web:ce26943bf5fbc705fb23ea',
    messagingSenderId: '233586415711',
    projectId: 'vigil-cloud-c9e28',
    authDomain: 'vigil-cloud-c9e28.firebaseapp.com',
    storageBucket: 'vigil-cloud-c9e28.firebasestorage.app',
    measurementId: 'G-YJKLZMFW3T',
  );

}