platform :ios, '13.0'

# CocoaPods analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end